#!/usr/bin/env python3
import argparse
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE_JSON = ROOT / 'data' / 'site.json'


def git(repo_path, *args):
    return subprocess.check_output(['git', *args], cwd=repo_path, text=True).strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--repo-path', required=True)
    ap.add_argument('--repo', required=True)
    ap.add_argument('--pr-number', required=True, type=int)
    ap.add_argument('--pr-url', required=True)
    ap.add_argument('--branch', required=False)
    ap.add_argument('--commit', required=False)
    ap.add_argument('--slug', required=True)
    ap.add_argument('--title', required=True)
    ap.add_argument('--summary', required=True)
    ap.add_argument('--status', default='open')
    args = ap.parse_args()

    repo_path = Path(args.repo_path)
    branch = args.branch or git(repo_path, 'branch', '--show-current')
    commit = args.commit or git(repo_path, 'rev-parse', 'HEAD')
    date = git(repo_path, 'show', '-s', '--format=%cs', commit)
    diff_stat = git(repo_path, 'show', '--stat', '--format=', commit).strip().splitlines()
    diff_stat = diff_stat[-1].strip() if diff_stat else ''
    files_changed = [line.split('|')[0].strip() for line in git(repo_path, 'show', '--name-only', '--format=', commit).splitlines() if line.strip()]
    commit_subject = git(repo_path, 'show', '-s', '--format=%s', commit)

    payload = json.loads(SITE_JSON.read_text())
    posts = payload['posts']
    posts = [p for p in posts if p.get('slug') != args.slug]
    posts.append({
        'slug': args.slug,
        'title': args.title,
        'date': date,
        'repo': args.repo,
        'pr_number': args.pr_number,
        'pr_url': args.pr_url,
        'status': args.status,
        'branch': branch,
        'commit': commit,
        'summary': args.summary,
        'problem': [f'Autogenerated from commit {commit_subject}.'],
        'changes': [f'Updated files captured from git for branch {branch}.'],
        'tests': ['Add test results manually if needed.'],
        'files_changed': files_changed,
        'diff_stat': diff_stat,
        'lessons': ['Review and enrich this autogenerated draft before publishing externally if higher polish is needed.']
    })
    payload['posts'] = sorted(posts, key=lambda p: p['date'], reverse=True)
    SITE_JSON.write_text(json.dumps(payload, indent=2) + '\n')
    print(f'upserted {args.slug}')


if __name__ == '__main__':
    main()
