#!/usr/bin/env bash
set -euo pipefail
if [ "$#" -lt 6 ]; then
  echo "usage: $0 <repo-path> <owner/repo> <pr-number> <pr-url> <slug> <title> [summary]"
  exit 1
fi
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_PATH="$1"
REPO_NAME="$2"
PR_NUMBER="$3"
PR_URL="$4"
SLUG="$5"
TITLE="$6"
SUMMARY="${7:-Autogenerated post draft from completed PR work.}"
python3 "$ROOT/scripts/add_post_from_git.py" \
  --repo-path "$REPO_PATH" \
  --repo "$REPO_NAME" \
  --pr-number "$PR_NUMBER" \
  --pr-url "$PR_URL" \
  --slug "$SLUG" \
  --title "$TITLE" \
  --summary "$SUMMARY"
python3 "$ROOT/scripts/sync_site.py"
"$ROOT/scripts/deploy_local.sh"
"$ROOT/scripts/publish_if_possible.sh"
